package cn.llonvne.type

interface ApiNamePolicy {

    fun generateName(apiImplement: ApiImplement): String

    data object AutoGenerated : ApiNamePolicy {
        override fun generateName(apiImplement: ApiImplement): String {
            return apiImplement.apiCls().simpleName ?: "unknown"
        }
    }

    data class Specified(val name: String) : ApiNamePolicy {
        override fun generateName(apiImplement: ApiImplement): String {
            return name
        }
    }
}