package cn.llonvne.type

sealed interface UriPolicy {

        fun getUri(apiImplement: ApiImplement): String

        data class Specified(val uri: String) : UriPolicy {
            override fun getUri(apiImplement: ApiImplement): String {
                return uri
            }
        }

        data object AutoGenerated : UriPolicy {
            override fun getUri(apiImplement: ApiImplement): String {
                return apiImplement.apiCls().simpleName ?: "unknown"
            }
        }
    }